In [1]:
import os
import numpy as np
import pandas as pd


os.chdir(r'D:\Work\景观格局指标对PM2.5影响')

In [2]:
targets = pd.read_excel("建模数据/因变量.xlsx", index_col=0, usecols=[0, 1])
targets

       2.5_spring
SID
S1_3           54
S2_3           48
S3_3           66
S5_3           42
S6_3           39
S7_3           58
S8_3           38
S11_3          28
S12_3          50
S13_3          67
S14_3          47
S15_3          47
S16_3          41
S17_3          30
S19_3          41
S20_3          34
S21_3          33
S22_3          23
S23_3          40
S1_4           40
S2_4           46
S3_4           56
S5_4           52
S6_4           31
S7_4           49
S8_4           23
S11_4          21
S12_4          43
S13_4          39
S14_4          43
S15_4          32
S16_4          33
S17_4          24
S19_4          37
S20_4          27
S21_4          25
S22_4          20
S23_4          37
S1_5           36
S2_5           51
S3_5           58
S5_5           51
S6_5           28
S7_5           47
S8_5           20
S11_5          32
S12_5          45
S13_5          24
S14_5          44
S15_5          37
S16_5          36
S17_5          27
S19_5          39
S20_5          34
S21_5          30
S22_5          30
S23_5          46

In [3]:
features = pd.read_excel("建模数据/自变量/01-Spring.xlsx", index_col=0)
features

,PREC,T2m,SP,RH,WS10,Dproad_300,Dproad_600,Dproad_900,Dproad_1200,Dproad_2400,...,ILP1200,ILP2400,ILP4800,Dt_eco,DPop_300,DPop_600,DPop_900,DPop_1200,DPop_2400,DPop_4800
SID,,,,,,,,,,,,,,,,,,,,,
S1_3,6.212903,12.984705,1017.157812,81.044292,1.270939,0.001265,0.004886,0.004276,0.003283,0.002129,...,0.000000,0.000000,2.171891,361.632300,0.019169,0.016845,0.019158,0.019414,0.020521,0.011583
S2_3,6.280645,12.958002,1015.867734,81.091632,1.284600,0.003665,0.005060,0.003766,0.003040,0.002945,...,1.292960,0.803401,1.049734,537.144125,0.022517,0.021921,0.019917,0.018502,0.023245,0.016714
S3_3,6.367742,13.055841,1018.716406,81.228142,1.338889,0.003867,0.002079,0.001404,0.002006,0.003388,...,31.572690,13.616941,5.423209,1703.372833,0.052762,0.043114,0.032077,0.023952,0.013400,0.010296
S5_3,6.367742,13.045435,1018.661484,81.308019,1.326964,0.004046,0.002140,0.002409,0.002014,0.001435,...,2.321013,7.648153,11.134880,2683.988108,0.004553,0.005657,0.007263,0.008037,0.007419,0.007594
S6_3,6.548387,13.038751,1017.229922,81.423260,1.388808,0.000000,0.000683,0.001152,0.002268,0.002263,...,0.000000,0.965198,9.131623,5486.573978,0.009205,0.010116,0.010849,0.011473,0.007790,0.002967
S7_3,6.493548,13.061334,1018.043359,81.348051,1.385824,0.000000,0.000000,0.000000,0.000941,0.002060,...,23.834006,28.784985,22.742945,7849.329414,0.002952,0.002335,0.001952,0.002103,0.002421,0.002614
S8_3,6.135484,12.705194,1008.021484,81.000024,1.201916,0.003186,0.006046,0.004468,0.004243,0.003037,...,2.888627,5.175177,3.513949,3083.411209,0.001526,0.001420,0.001571,0.001918,0.003002,0.002717
S11_3,6.364516,13.057428,1019.409531,81.367492,1.313293,0.003883,0.002144,0.002812,0.002862,0.001794,...,9.063763,6.784877,8.813477,527.706011,0.003108,0.003631,0.003809,0.003777,0.003236,0.003464
S12_3,6.216129,12.875787,1013.265469,81.078725,1.260117,0.002062,0.002932,0.004135,0.003471,0.002467,...,0.000000,0.000000,0.648915,901.066982,0.002692,0.003118,0.003076,0.002730,0.002438,0.004629
S13_3,6.103226,12.804315,1011.700547,80.951858,1.209034,0.000000,0.000000,0.000000,0.000000,0.001808,...,4.343696,7.059114,9.539998,1914.404841,0.006768,0.006084,0.004448,0.003607,0.003408,0.003411
S14_3,6.090323,12.742426,1009.568438,80.970521,1.192935,0.000000,0.000188,0.003521,0.003964,0.002068,...,12.406718,11.534109,8.609789,2043.234885,0.006208,0.006327,0.006535,0.006899,0.004862,0.003757
S15_3,6.264516,12.995081,1017.193359,81.051332,1.282512,0.000000,0.001012,0.001978,0.001852,0.002231,...,0.000000,0.000000,0.734072,1625.627120,0.028332,0.029450,0.029617,0.028811,0.030586,0.019361
S16_3,6.264516,12.970758,1016.425156,81.046391,1.275795,0.000000,0.000000,0.000566,0.002543,0.002365,...,0.000000,0.000000,0.637490,1257.451797,0.031311,0.028292,0.027921,0.027182,0.030982,0.018909
S17_3,6.309677,13.034296,1018.140781,81.148206,1.318800,0.004004,0.004409,0.003684,0.003163,0.003902,...,4.598862,3.338493,4.530064,187.102859,0.025941,0.024009,0.022762,0.021752,0.021865,0.015469
S19_3,6.290323,13.023950,1018.188203,81.158271,1.294976,0.000000,0.000000,0.001478,0.003229,0.002231,...,0.000000,1.711987,3.822138,679.170872,0.007797,0.008593,0.009094,0.010397,0.013337,0.014868
S20_3,6.290323,13.042535,1019.050625,81.276877,1.297243,0.000000,0.001148,0.001638,0.001442,0.001469,...,14.333631,14.047402,8.349815,403.966994,0.003103,0.003079,0.002899,0.002714,0.002211,0.003360
S21_3,6.193548,12.873499,1013.352266,81.026615,1.248947,0.000000,0.002950,0.002804,0.002364,0.003233,...,0.000000,0.326062,0.643311,656.934708,0.009458,0.011431,0.010774,0.010223,0.008994,0.011676
S22_3,6.032258,12.643854,1006.455703,80.980413,1.156311,0.002484,0.002522,0.002368,0.001903,0.001481,...,20.434717,14.695674,8.373041,989.735047,0.003322,0.002552,0.002441,0.002475,0.002764,0.002843
S23_3,6.429032,13.073602,1019.092344,81.283683,1.360840,0.000000,0.001741,0.004983,0.003871,0.003000,...,4.858425,8.727099,5.770153,1615.988212,0.002616,0.002341,0.001986,0.001720,0.002595,0.004651
S1_4,6.636667,19.245264,1011.777656,80.118971,0.784602,0.001265,0.004886,0.004276,0.003283,0.002129,...,0.000000,0.000000,2.171891,361.632300,0.019169,0.016845,0.019158,0.019414,0.020521,0.011583
S2_4,6.663333,19.240717,1010.536641,80.053891,0.806782,0.003665,0.005060,0.003766,0.003040,0.002945,...,1.292960,0.803401,1.049734,537.144125,0.022517,0.021921,0.019917,0.018502,0.023245,0.016714
S3_4,6.696667,19.389215,1013.315156,80.008430,0.858553,0.003867,0.002079,0.001404,0.002006,0.003388,...,31.572690,13.616941,5.423209,1703.372833,0.052762,0.043114,0.032077,0.023952,0.013400,0.010296
S5_4,6.703333,19.374139,1013.257734,80.175773,0.844376,0.004046,0.002140,0.002409,0.002014,0.001435,...,2.321013,7.648153,11.134880,2683.988108,0.004553,0.005657,0.007263,0.008037,0.007419,0.007594
S6_4,6.756667,19.446710,1011.893594,80.021515,0.913782,0.000000,0.000683,0.001152,0.002268,0.002263,...,0.000000,0.965198,9.131623,5486.573978,0.009205,0.010116,0.010849,0.011473,0.007790,0.002967
S7_4,6.750000,19.456659,1012.678281,79.940202,0.911311,0.000000,0.000000,0.000000,0.000941,0.002060,...,23.834006,28.784985,22.742945,7849.329414,0.002952,0.002335,0.001952,0.002103,0.002421,0.002614
S8_4,6.593333,18.919580,1002.902109,80.176590,0.733185,0.003186,0.006046,0.004468,0.004243,0.003037,...,2.888627,5.175177,3.513949,3083.411209,0.001526,0.001420,0.001571,0.001918,0.003002,0.002717
S11_4,6.706667,19.372247,1013.975781,80.341963,0.828536,0.003883,0.002144,0.002812,0.002862,0.001794,...,9.063763,6.784877,8.813477,527.706011,0.003108,0.003631,0.003809,0.003777,0.003236,0.003464
S12_4,6.623333,19.146417,1008.009766,80.076728,0.788913,0.002062,0.002932,0.004135,0.003471,0.002467,...,0.000000,0.000000,0.648915,901.066982,0.002692,0.003118,0.003076,0.002730,0.002438,0.004629
S13_4,6.606667,19.008417,1006.461484,80.164776,0.725481,0.000000,0.000000,0.000000,0.000000,0.001808,...,4.343696,7.059114,9.539998,1914.404841,0.006768,0.006084,0.004448,0.003607,0.003408,0.003411
S14_4,6.603333,18.935266,1004.390625,80.219407,0.714057,0.000000,0.000188,0.003521,0.003964,0.002068,...,12.406718,11.534109,8.609789,2043.234885,0.006208,0.006327,0.006535,0.006899,0.004862,0.003757
S15_4,6.666667,19.267328,1011.818516,80.072883,0.799071,0.000000,0.001012,0.001978,0.001852,0.002231,...,0.000000,0.000000,0.734072,1625.627120,0.028332,0.029450,0.029617,0.028811,0.030586,0.019361
S16_4,6.666667,19.238245,1011.071719,80.080766,0.793554,0.000000,0.000000,0.000566,0.002543,0.002365,...,0.000000,0.000000,0.637490,1257.451797,0.031311,0.028292,0.027921,0.027182,0.030982,0.018909
S17_4,6.663333,19.345270,1012.750234,80.003456,0.838504,0.004004,0.004409,0.003684,0.003163,0.003902,...,4.598862,3.338493,4.530064,187.102859,0.025941,0.024009,0.022762,0.021752,0.021865,0.015469
S19_4,6.670000,19.312006,1012.786484,80.159745,0.810420,0.000000,0.000000,0.001478,0.003229,0.002231,...,0.000000,1.711987,3.822138,679.170872,0.007797,0.008593,0.009094,0.010397,0.013337,0.014868
S20_4,6.676667,19.336206,1013.621406,80.307123,0.811300,0.000000,0.001148,0.001638,0.001442,0.001469,...,14.333631,14.047402,8.349815,403.966994,0.003103,0.003079,0.002899,0.002714,0.002211,0.003360
S21_4,6.630000,19.121881,1008.084609,80.112654,0.771547,0.000000,0.002950,0.002804,0.002364,0.003233,...,0.000000,0.326062,0.643311,656.934708,0.009458,0.011431,0.010774,0.010223,0.008994,0.011676
S22_4,6.603333,18.803156,1001.358125,80.328059,0.679797,0.002484,0.002522,0.002368,0.001903,0.001481,...,20.434717,14.695674,8.373041,989.735047,0.003322,0.002552,0.002441,0.002475,0.002764,0.002843
S23_4,6.693333,19.429681,1013.687344,79.965949,0.881594,0.000000,0.001741,0.004983,0.003871,0.003000,...,4.858425,8.727099,5.770153,1615.988212,0.002616,0.002341,0.001986,0.001720,0.002595,0.004651
S1_5,6.100000,23.093958,1009.178906,71.855988,0.859528,0.001265,0.004886,0.004276,0.003283,0.002129,...,0.000000,0.000000,2.171891,361.632300,0.019169,0.016845,0.019158,0.019414,0.020521,0.011583
S2_5,6.235484,23.026575,1007.951719,72.113048,0.876357,0.003665,0.005060,0.003766,0.003040,0.002945,...,1.292960,0.803401,1.049734,537.144125,0.022517,0.021921,0.019917,0.018502,0.023245,0.016714
S3_5,6.264516,23.191064,1010.679062,72.082452,0.908173,0.003867,0.002079,0.001404,0.002006,0.003388,...,31.572690,13.616941,5.423209,1703.372833,0.052762,0.043114,0.032077,0.023952,0.013400,0.010296
S5_5,6.151613,23.187311,1010.628672,72.073881,0.894834,0.004046,0.002140,0.002409,0.002014,0.001435,...,2.321013,7.648153,11.134880,2683.988108,0.004553,0.005657,0.007263,0.008037,0.007419,0.007594
S6_5,6.287097,23.143793,1009.279141,72.350420,0.940011,0.000000,0.000683,0.001152,0.002268,0.002263,...,0.000000,0.965198,9.131623,5486.573978,0.009205,0.010116,0.010849,0.011473,0.007790,0.002967
S7_5,6.332258,23.178278,1010.049766,72.277991,0.942638,0.000000,0.000000,0.000000,0.000941,0.002060,...,23.834006,28.784985,22.742945,7849.329414,0.002952,0.002335,0.001952,0.002103,0.002421,0.002614
S8_5,6.303226,22.600366,1000.446797,72.405450,0.830390,0.003186,0.006046,0.004468,0.004243,0.003037,...,2.888627,5.175177,3.513949,3083.411209,0.001526,0.001420,0.001571,0.001918,0.003002,0.002717
S11_5,6.100000,23.218195,1011.340312,72.018567,0.882992,0.003883,0.002144,0.002812,0.002862,0.001794,...,9.063763,6.784877,8.813477,527.706011,0.003108,0.003631,0.003809,0.003777,0.003236,0.003464
S12_5,6.274194,22.880884,1005.465781,72.311343,0.867698,0.002062,0.002932,0.004135,0.003471,0.002467,...,0.000000,0.000000,0.648915,901.066982,0.002692,0.003118,0.003076,0.002730,0.002438,0.004629
S13_5,6.174194,22.800714,1003.951641,71.959441,0.822436,0.000000,0.000000,0.000000,0.000000,0.001808,...,4.343696,7.059114,9.539998,1914.404841,0.006768,0.006084,0.004448,0.003607,0.003408,0.003411
S14_5,6.274194,22.683862,1001.915000,72.140777,0.814898,0.000000,0.000188,0.003521,0.003964,0.002068,...,12.406718,11.534109,8.609789,2043.234885,0.006208,0.006327,0.006535,0.006899,0.004862,0.003757
S15_5,6.235484,23.096826,1009.216484,71.946379,0.869439,0.000000,0.001012,0.001978,0.001852,0.002231,...,0.000000,0.000000,0.734072,1625.627120,0.028332,0.029450,0.029617,0.028811,0.030586,0.019361
S16_5,6.235484,23.055353,1008.482031,71.983426,0.866188,0.000000,0.000000,0.000566,0.002543,0.002365,...,0.000000,0.000000,0.637490,1257.451797,0.031311,0.028292,0.027921,0.027182,0.030982,0.018909
S17_5,6.190323,23.154382,1010.125703,72.043428,0.896055,0.004004,0.004409,0.003684,0.003163,0.003902,...,4.598862,3.338493,4.530064,187.102859,0.025941,0.024009,0.022762,0.021752,0.021865,0.015469
S19_5,6.100000,23.151117,1010.169297,71.958015,0.874933,0.000000,0.000000,0.001478,0.003229,0.002231,...,0.000000,1.711987,3.822138,679.170872,0.007797,0.008593,0.009094,0.010397,0.013337,0.014868
S20_5,6.090323,23.194116,1010.992969,71.946863,0.873666,0.000000,0.001148,0.001638,0.001442,0.001469,...,14.333631,14.047402,8.349815,403.966994,0.003103,0.003079,0.002899,0.002714,0.002211,0.003360
S21_5,6.235484,22.889429,1005.544141,72.132294,0.853193,0.000000,0.002950,0.002804,0.002364,0.003233,...,0.000000,0.326062,0.643311,656.934708,0.009458,0.011431,0.010774,0.010223,0.008994,0.011676
S22_5,6.241935,22.511896,998.934141,72.306516,0.792087,0.002484,0.002522,0.002368,0.001903,0.001481,...,20.434717,14.695674,8.373041,989.735047,0.003322,0.002552,0.002441,0.002475,0.002764,0.002843
S23_5,6.254839,23.216394,1011.040938,72.143253,0.924099,0.000000,0.001741,0.004983,0.003871,0.003000,...,4.858425,8.727099,5.770153,1615.988212,0.002616,0.002341,0.001986,0.001720,0.002595,0.004651

In [4]:
features_scaled = features.apply(lambda x: (x - x.min()) / (x.max() - x.min()))

In [5]:
def adjusted_r2(r2, n, p):
    return 1 - (1 - r2) * (n - 1) / (n - p - 1)

In [6]:
def calcMrer(y_true, y_pred):
    """
    计算MRER
    :param y_true: 实际值数组
    :param y_pred: 预测值数组
    :return: MRER值
    """
    relative_errors = np.abs((y_pred - y_true) / y_true)
    return np.mean(relative_errors)

In [88]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
        features_scaled[['ELP1200', 'SP', 'ILP1200']].values, targets.values.reshape(-1), train_size=0.8, test_size=0.2, random_state=1)

In [89]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()

# 训练模型
model.fit(X_train, y_train)

# 预测
y_pred = model.predict(X_test)

In [90]:
n = X_test.shape[0]
p =  X_test.shape[1]-1
print('系数:', model.coef_)
print('截距:', model.intercept_)
mse = mean_squared_error(y_test, y_pred)
print('标准估计误差see:', np.sqrt(mse * n / (n - p - 1)))
print('均方误差(MSE):', mse)
print('均方根误差(RMSE):', np.sqrt(mse))
r2 = r2_score(y_test, y_pred)
print("R2分数:", r2)
print('调整R2分数:', adjusted_r2(r2, n, p))
mrer = calcMrer(y_test, y_pred)
print("MRER: ", mrer)

系数: [-11.76008407  12.3447971    6.07319445]
截距: 35.083549484341155
标准估计误差see: 8.336039371593413
均方误差(MSE): 52.117164303566625
均方根误差(RMSE): 7.219221862747164
R2分数: 0.6688637636907169
调整R2分数: 0.5952779333997651
MRER:  0.15436043622794246

In [94]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
        features[['ELP1200', 'SP', 'ILP1200']].values, targets.values.reshape(-1), train_size=0.8, test_size=0.2, random_state=1)

In [57]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

# 定义参数网格
param_grid = {
    # 'n_estimators': list(range(10, 200, 5)),
    # 'max_depth': list(range(1, 50, 2))
    'max_features': list(range(1, 50, 2))
}

# 创建网格搜索对象
grid_search = GridSearchCV(
    estimator=RandomForestRegressor(
        n_estimators=75,
        max_depth=5,
        min_samples_leaf=2,
        min_samples_split=2,
        random_state=1),
    param_grid=param_grid,
    cv=5,
    n_jobs=24,
    verbose=2
)

# 执行网格搜索
grid_search.fit(X_train, y_train)

# 输出最佳参数
print("最佳参数:", grid_search.best_params_)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
最佳参数: {'max_features': 3}

In [95]:
from sklearn.ensemble import RandomForestRegressor

rf_regressor = RandomForestRegressor(n_estimators=75,
                                     max_depth=5,
                                     min_samples_leaf=2,
                                     min_samples_split=2,
                                     max_features=3,
                                     random_state=1)

# 训练模型
rf_regressor.fit(X_train, y_train)

# 预测
y_pred = rf_regressor.predict(X_test)

In [96]:
n = X_test.shape[0]
p =  X_test.shape[1]-1
mse = mean_squared_error(y_test, y_pred)
print('标准估计误差see:', np.sqrt(mse * n / (n - p - 1)))
print('均方误差(MSE):', mse)
print('均方根误差(RMSE):', np.sqrt(mse))
r2 = r2_score(y_test, y_pred)
print("R2分数:", r2)
print('调整R2分数:', adjusted_r2(r2, n, p))
mrer = calcMrer(y_test, y_pred)
print("MRER: ", mrer)

标准估计误差see: 10.425444685394783
均方误差(MSE): 81.51742266616974
均方根误差(RMSE): 9.028699943301346
R2分数: 0.4820636752590699
调整R2分数: 0.36696671420552984
MRER:  0.19911201185347138